### ISSUE TITLE
Glance image-create fails with API v2

### ISSUE THREAD

**Issue by andybotting** [NeCTAR-RC/bugs#6]
Attempting to create a new Glance image using Glance API v2 fails:

```
$ glance image-create --progress --file centos7.qcow2 --name 'delete-temp-image' --container-format=bare --disk-format=qcow2
```

Output:
`HTTPInternalServerError (HTTP 500)`

The Glance API server logs show this:
Got error from Swift: Object DELETE failed: `https://swift.rc.nectar.org.au:8888/v1/AUTH_3/images/bc9d9757-30c0-4a32-8ee8-57376f2a3b7e-00004 404 Not Found  [first 60 chars of response] <html><h1>Not Found</h1><p>The resource could not be found.<`

Swift does not show any errors, except that a DELETE request does result in a 404 message.

Using the command line options `--os-image-api-version=1` to Glance results in a successful image creation.

I have been unable to reproduce this in our test environment.

**Comment by sorrison** [comment]
Is this still happening?

**Comment by sorrison** [comment]
Pretty sure this is fixed?

**Comment by andybotting** [comment]
Glance client gives me this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/glanceclient/shell.py", line 595, in main
    args.func(client, args)
  File "/usr/lib/python3.5/site-packages/glanceclient/common/utils.py", line 98, in func_wrapper
    return func(gc, args)
  File "/usr/lib/python3.5/site-packages/glanceclient/v2/shell.py", line 85, in do_image_create
    image = gc.images.get(args.id)
  File "/usr/lib/python3.5/site-packages/glanceclient/v2/images.py", line 181, in get
    resp, body = self.http_client.get(url)
  File "/usr/lib/python3.5/site-packages/keystoneclient/adapter.py", line 176, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python3.5/site-packages/glanceclient/common/http.py", line 332, in request
    return self._handle_response(resp)
  File "/usr/lib/python3.5/site-packages/glanceclient/common/http.py", line 83, in _handle_response
    raise exc.from_response(resp, resp.content)
glanceclient.exc.HTTPBadRequest: Error response: Error code 400.: Message: Bad request syntax ('0').: Error code explanation: 400 = Bad request syntax or unsupported method. (HTTP 400)
Error response: Error code 400.: Message: Bad request syntax ('0').: Error code explanation: 400 = Bad request syntax or unsupported method. (HTTP 400)
```

The image does appear to be in the glance image-list though.

Works fine with v1

**Comment by sorrison** [comment]
What version of glance client? I tried it with version 2.0.0 and it worked fine

**Comment by sorrison** [comment]
Old and fixed
