### ISSUE TITLE
Creating volume from a qcow2 image needs larger volume

### ISSUE THREAD

**Issue by sirswa** [NeCTAR-RC/bugs#8]
When creating volume from a qcow2 image needs much larger volume size due to converting to raw format
Creating volume same size as qcow2 image (default in Dashboard) will result in error after few minutes of creating. Users are not aware that they need to create larger volume from failure error message.

Related helpdesk ticket https://support.nectar.org.au/helpdesk/tickets/1336

Example:
image:

Error in cinder-volume.log
`2016-02-19 15:34:50.431 20733 ERROR cinder.volume.flows.manager.create_volume [req-edc9cb0d-2069-4fdb-b9d1-8fc24ef59564 b3ee0f7c8dcb4c32b9854b90cc94973a 05bc781fd9684698872463cbc4fbdcd2 - - -] Failed to copy image to volume: e2b07539-7201-41f8-be12-fd366a820ec2
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume Traceback (most recent call last):
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 501, in _copy_image_to_volume
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume     copy_image_to_volume(context, volume_ref, image_service, image_id)
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume   File "/usr/lib/python2.7/dist-packages/osprofiler/profiler.py", line 105, in wrapper
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume     return f(*args, **kwargs)
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume   File "/usr/lib/python2.7/dist-packages/cinder/volume/drivers/rbd.py", line 858, in copy_image_to_volume
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume     size=volume['size'])
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume   File "/usr/lib/python2.7/dist-packages/cinder/image/image_utils.py", line 226, in fetch_to_raw
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume     run_as_root=run_as_root)
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume   File "/usr/lib/python2.7/dist-packages/cinder/image/image_utils.py", line 293, in fetch_to_volume_format
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume     raise exception.ImageUnacceptable(image_id=image_id, reason=reason)
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume ImageUnacceptable: Image 06d27916-df15-405f-aeb5-e560fe4eea44 is unacceptable: Size is 30GB and doesn't fit in a volume of size 25GB.
2016-02-19 15:34:50.431 20733 TRACE cinder.volume.flows.manager.create_volume 
2016-02-19 15:34:50.436 20733 WARNING cinder.volume.manager [req-edc9cb0d-2069-4fdb-b9d1-8fc24ef59564 b3ee0f7c8dcb4c32b9854b90cc94973a 05bc781fd9684698872463cbc4fbdcd2 - - -] Task 'cinder.volume.flows.manager.create_volume.CreateVolumeFromSpecTask;volume:create' (5a34b284-6a06-4aba-95ad-b81b9e523aaa) transitioned into state 'FAILURE' from state 'RUNNING'
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager Traceback (most recent call last):
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/taskflow/engines/action_engine/executor.py", line 67, in _execute_task
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager     result = task.execute(**arguments)
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 653, in execute
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager     **volume_spec)
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 605, in _create_from_image
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager     image_id, image_location, image_service)
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager   File "/usr/lib/python2.7/dist-packages/cinder/volume/flows/manager/create_volume.py", line 510, in _copy_image_to_volume
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager     raise exception.ImageUnacceptable(ex)
2016-02-19 15:34:50.436 20733 TRACE cinder.volume.manager ImageUnacceptable: Image 06d27916-df15-405f-aeb5-e560fe4eea44 is unacceptable: Size is 30GB and doesn't fit in a volume of size 25GB.
`

**Comment by sorrison** [comment]
Hmm ok, so basically this looks like a case where horion needs to give the user this error. Do you get an error if you do it via the command line?

**Comment by sirswa** [comment]
no, it did not show error in command line. It went to creating and cinder show status changed to "error" from "downloading" later.

`cinder create --image-id 06d27916-df15-405f-aeb5-e560fe4eea44 --name swe-vol-25G --availability-zone monash-02 25
+---------------------------------------+--------------------------------------+
|                Property               |                Value                 |
+---------------------------------------+--------------------------------------+
|              attachments              |                  []                  |
|           availability_zone           |              monash-02               |
|                bootable               |                false                 |
|          consistencygroup_id          |                 None                 |
|               created_at              |      2016-02-22T01:02:15.000000      |
|              description              |                 None                 |
|               encrypted               |                False                 |
|                   id                  | 0ada1730-5c1d-4cd1-b40c-c390352af7c7 |
|                metadata               |                  {}                  |
|              multiattach              |                False                 |
|                  name                 |             swe-vol-25G              |
|      os-vol-tenant-attr:tenant_id     |   d57d0879288840e199bb1a49ae012c78   |
|   os-volume-replication:driver_data   |                 None                 |
| os-volume-replication:extended_status |                 None                 |
|           replication_status          |               disabled               |
|                  size                 |                  25                  |
|              snapshot_id              |                 None                 |
|              source_volid             |                 None                 |
|                 status                |               creating               |
|                user_id                |   58326623fd30452d9c578fcdca7b7685   |
|              volume_type              |                monash                |
+---------------------------------------+--------------------------------------+

➜  ~  cinder show 0ada1730-5c1d-4cd1-b40c-c390352af7c7
+---------------------------------------+--------------------------------------+
|                Property               |                Value                 |
+---------------------------------------+--------------------------------------+
|              attachments              |                  []                  |
|           availability_zone           |              monash-02               |
|                bootable               |                false                 |
|          consistencygroup_id          |                 None                 |
|               created_at              |      2016-02-22T01:02:15.000000      |
|              description              |                 None                 |
|               encrypted               |                False                 |
|                   id                  | 0ada1730-5c1d-4cd1-b40c-c390352af7c7 |
|                metadata               |                  {}                  |
|              multiattach              |                False                 |
|                  name                 |             swe-vol-25G              |
|         os-vol-host-attr:host         |          rccinder02-01#RBD           |
|     os-vol-mig-status-attr:migstat    |                 None                 |
|     os-vol-mig-status-attr:name_id    |                 None                 |
|      os-vol-tenant-attr:tenant_id     |   d57d0879288840e199bb1a49ae012c78   |
|   os-volume-replication:driver_data   |                 None                 |
| os-volume-replication:extended_status |                 None                 |
|           replication_status          |               disabled               |
|                  size                 |                  25                  |
|              snapshot_id              |                 None                 |
|              source_volid             |                 None                 |
|                 status                |             downloading              |
|                user_id                |   58326623fd30452d9c578fcdca7b7685   |
|              volume_type              |                monash                |
+---------------------------------------+--------------------------------------+

➜  ~  cinder show 0ada1730-5c1d-4cd1-b40c-c390352af7c7
+---------------------------------------+--------------------------------------+
|                Property               |                Value                 |
+---------------------------------------+--------------------------------------+
|              attachments              |                  []                  |
|           availability_zone           |              monash-02               |
|                bootable               |                false                 |
|          consistencygroup_id          |                 None                 |
|               created_at              |      2016-02-22T01:02:15.000000      |
|              description              |                 None                 |
|               encrypted               |                False                 |
|                   id                  | 0ada1730-5c1d-4cd1-b40c-c390352af7c7 |
|                metadata               |                  {}                  |
|              multiattach              |                False                 |
|                  name                 |             swe-vol-25G              |
|         os-vol-host-attr:host         |          rccinder02-01#RBD           |
|     os-vol-mig-status-attr:migstat    |                 None                 |
|     os-vol-mig-status-attr:name_id    |                 None                 |
|      os-vol-tenant-attr:tenant_id     |   d57d0879288840e199bb1a49ae012c78   |
|   os-volume-replication:driver_data   |                 None                 |
| os-volume-replication:extended_status |                 None                 |
|           replication_status          |               disabled               |
|                  size                 |                  25                  |
|              snapshot_id              |                 None                 |
|              source_volid             |                 None                 |
|                 status                |                error                 |
|                user_id                |   58326623fd30452d9c578fcdca7b7685   |
|              volume_type              |                monash                |
+---------------------------------------+--------------------------------------+

`
