### ISSUE TITLE
Cinder DB connections not re-attempted

### ISSUE THREAD

**Issue by mead** [NeCTAR-RC/bugs#9]
Unclear what the particular bug is, but the resulting state is that volume creation fails. 
Problem can be detected by cinder-volume no longer having connections to the cinder database.

```
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 ERROR cinder.openstack.common.loopingcall [req-06b74293-79b8-42ed-b6bf-712c69e40341 - - - - -] in fixed duration looping call
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall Traceback (most recent call last):
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/loopingcall.py", line 81, in _inner
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     self.f(*self.args, **self.kw)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/service.py", line 307, in report_state
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     self.service_id, state_catalog)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/api.py", line 130, in service_update
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return IMPL.service_update(context, service_id, values)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 163, in wrapper
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return f(*args, **kwargs)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 439, in service_update
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     service_ref = _service_get(context, service_id, session=session)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 163, in wrapper
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return f(*args, **kwargs)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 348, in _service_get
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     filter_by(id=service_id).\
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     ret = list(self[0:1])
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return list(res)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return self._execute_and_instances(context)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     close_with_result=True)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     **kw)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     close_with_result=close_with_result)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return self.transaction._connection_for_bind(engine)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     conn = bind.contextual_connect()
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 208, in contextual_connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     self._wrap_pool_connect(self.pool.connect, None),
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 219, in _wrap_pool_connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     e, dialect, self)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 324, in _handle_dbapi_exception_noconnection
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     six.reraise(type(newraise), newraise, exc_info[2])
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 215, in _wrap_pool_connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return fn()
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     return _ConnectionFairy._checkout(self)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     fairy = _ConnectionRecord.checkout(pool)
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 442, in checkout
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     dbapi_connection = rec.get_connection()
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 526, in get_connection
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     self.connection = self.__connect()
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 538, in __connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     connection = self.__pool._creator()
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 200, in connect
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall     raise original_exception
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall OperationalError: (OperationalError) (2005, "Unknown MySQL server host 'db-cinder.rc.nectar.org.au' (0)") None None
/var/log/cinder/cinder-volume.log.4.gz:2016-04-27 06:36:49.738 12436 TRACE cinder.openstack.common.loopingcall 
```

**Comment by mead** [comment]
We're now monitoring the db connection. This log entry matches the observed loss of db connection:

```
2016-05-14 22:28:25.795 31748 ERROR cinder.openstack.common.loopingcall [req-c2e782f2-302c-4a85-85fe-662e251d4429 - - - - -] in fixed duration looping call
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall Traceback (most recent call last):
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/openstack/common/loopingcall.py", line 81, in _inner
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     self.f(*self.args, **self.kw)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/service.py", line 307, in report_state
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     self.service_id, state_catalog)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/api.py", line 130, in service_update
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return IMPL.service_update(context, service_id, values)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 163, in wrapper
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return f(*args, **kwargs)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 439, in service_update
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     service_ref = _service_get(context, service_id, session=session)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 163, in wrapper
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return f(*args, **kwargs)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/cinder/db/sqlalchemy/api.py", line 348, in _service_get
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     filter_by(id=service_id).\
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2367, in first
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     ret = list(self[0:1])
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2228, in __getitem__
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return list(res)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return self._execute_and_instances(context)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2451, in _execute_and_instances
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     close_with_result=True)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2442, in _connection_from_session
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     **kw)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 854, in connection
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     close_with_result=close_with_result)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 858, in _connection_for_bind
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return self.transaction._connection_for_bind(engine)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 322, in _connection_for_bind
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     conn = bind.contextual_connect()
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 208, in contextua
l_connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     self._wrap_pool_connect(self.pool.connect, None),
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 219, in _wrap_poo
l_connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     e, dialect, self)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 324, in _handle_d
bapi_exception_noconnection
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     six.reraise(type(newraise), newraise, exc_info[2])
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 215, in _wrap_poo
l_connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return fn()
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 338, in connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     return _ConnectionFairy._checkout(self)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 644, in _checkout
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     fairy = _ConnectionRecord.checkout(pool)
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 442, in checkout
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     dbapi_connection = rec.get_connection()
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 526, in get_connection
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     self.connection = self.__connect()
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 538, in __connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     connection = self.__pool._creator()
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall   File "/usr/lib/python2.7/dist-packages/oslo_db/sqlalchemy/compat/handle_error.py", line 200, in connect
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall     raise original_exception
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall OperationalError: (OperationalError) (2005, "Unknown MySQL server host 'db-cinder.rc.nectar.org.au' (0)") N
one None
2016-05-14 22:28:25.795 31748 TRACE cinder.openstack.common.loopingcall
```

**Comment by sorrison** [comment]
Would be interested if this is still happening in liberty

**Comment by sorrison** [comment]
old and fixed
